name: Build

on:
  pull_request:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login --password-stdin --username ${{ github.actor }} ghcr.io

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: make build DOCKER_IMAGE_TAG=${{ steps.version.outputs.contents }} DOCKER_IMAGE_PLATFORM=linux/amd64,linux/arm64
