name: Push

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'

jobs:
  push:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login --password-stdin --username ${{ github.actor }} ghcr.io

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version
        id: version
        run: |
          echo "contents<<VERSIONEOF" >> $GITHUB_OUTPUT
          echo "$GITHUB_REF" | cut -d / -f 3 >> $GITHUB_OUTPUT
          echo "VERSIONEOF" >> $GITHUB_OUTPUT

      - name: Build and push
        run: make push DOCKER_IMAGE_TAG=${{ steps.version.outputs.contents }} DOCKER_IMAGE_PLATFORM=linux/amd64,linux/arm64
